name: Build Test Package

on:
  push:
    branches: [ master ]     
    paths:
      - source/MerriamWebster.NET
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x    
    - name: Setup .NET Core 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x        
    - name: Install dependencies
      run: dotnet restore ./source/MerriamWebster.NET/MerriamWebster.NET.sln
    - name: Build
      run: dotnet build ./source/MerriamWebster.NET/MerriamWebster.NET.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./source/MerriamWebster.NET/MerriamWebster.NET.sln --no-restore --verbosity normal
    - name: Publish to Nuget
      uses: alirezanet/publish-nuget@v3.0.4
      with: 
          PROJECT_FILE_PATH: ./source/MerriamWebster.NET/MerriamWebster.NET/MerriamWebster.NET.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    
