name: Build & Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore ./source/MerriamWebster.NET/MerriamWebster.NET.sln
    - name: Build
      run: dotnet build ./source/MerriamWebster.NET/MerriamWebster.NET.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./source/MerriamWebster.NET/MerriamWebster.NET.sln --no-restore --verbosity normal
